# frozen_string_literal: true

source "https://rubygems.org"


gem "dotenv", "~> 3.1"
gem "paypal-server-sdk", "~> 0.5.1"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"